### ISSUE TITLE
Building the project in Microsoft Visual Studio Community 2022

### ISSUE THREAD

**Issue by daimossomiad** [AudriusButkevicius/RemoteRuntime#1]
Anyone got it running in Microsoft Visual Studio Community 2022?
I get the retarget dialog (accept defaults) and then the build fails due to missing files:

![image](https://user-images.githubusercontent.com/96379138/181704330-7169a2e5-1758-4bbd-bb40-c5133835dfda.png)

![image](https://user-images.githubusercontent.com/96379138/181704447-00f1667a-e0b2-4551-b6aa-420e70fdc4f8.png)

Microsoft Visual Studio Community 2022
Version 17.0.4
VisualStudio.17.Release/17.0.4+32014.148
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA031
Microsoft Visual C++ 2022

ASP.NET and Web Tools 2019   17.0.795.42246
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.0.795.42246
Azure App Service Tools v3.0.0

C# Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.21293.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   6.0.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python - Profiling support   17.0.21293.2
Profiling support for Python projects.

Python with Pylance   17.0.21293.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.1001.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21522.2+6d626ff0752a77d339f609b4d361787dc9ca93a5
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

**Comment by AudriusButkevicius** [comment]
I suspect you need to setup vcpkg integration for vstudio 2022. I'm using Rider, so sadly can't help much.

**Comment by daimossomiad** [comment]
Indeed vcpkg helped, thanks!
